# Generated by Django 3.0.6 on 2021-03-27 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20210327_0258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
